apiVersion: apps/v1
kind: Deployment

metadata:
  name: my-java-app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: my-java-app

  template:
    metadata:
      labels:
        app: my-java-app

    spec:
      containers:
        - name: my-java-app
          image: kavya1111999/my-java-app:v6
          imagePullPolicy: Always

          ports:
            - containerPort: 8080
